image: openjdk:8-jdk-alpine
services:
    - docker:dind
variables:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_DRIVER: overlay

before_script:
stages:
    - build
    - deploy  
build_personnoeClient:
    image: maven:3-jdk-8
    stage: build
    script:
        - cd server/personne-client
        - ./mvnw clean package -DskipTests=true dockerfile:build 
deploy_personneClient:
    image: maven:3-jdk-8
    stage: deploy
    script:
        - cd server/personne-client
        - 'docker login -u "$user_docker" -p "$password_docker"'
        - ./mvnw dockerfile:push
