image: twalter/maven-docker
services:
      - docker:dind
variables:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_DRIVER: overlay

before_script:
        - docker login -u "$user_docker" -p "$password_docker"
stages:
    - build
    - deploy  
build_personnoeClient:
    stage: build
    script:
        - cd server/personne-client
        - ./mvnw clean package -DskipTests=true dockerfile:build 
    cache:
            key: "$CI_BUILD_REF"
            untracked: true
deploy_personneClient:
    stage: deploy
    script:
        - cd server/personne-client
        - ./mvnw dockerfile:push
    cache:
            key: "$CI_BUILD_REF"
            untracked: true
