image: twalter/maven-docker
services:
    - docker:dind
variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay

cache:
    key: ${CI_PROJECT_ID}
    paths:
        - .gradle/
        - node_modules/
stages:
    - build
    - deploy
    - build_Android

build_auth-service:
    stage: build
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/auth-service

build_configServer:
    stage: build
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/configServer
        - ./mvnw clean package -DskipTests=true dockerfile:build
        - ./mvnw clean package -DskipTests=true dockerfile:build
          
build_eurecka:
    stage: build
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/eureka-service
        - ./mvnw clean package -DskipTests=true dockerfile:build

build_FeedInfoService:
    stage: build
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/feedInfoService
        - ./mvnw clean package -DskipTests=true dockerfile:build


build_personneClient:
    stage: build
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/personne-client
        - ./mvnw clean package -DskipTests=true dockerfile:build

build_personneService:
    stage: build
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/personne-service
        - ./mvnw clean package -DskipTests=true dockerfile:build
build_webApp:
    stage: build
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/webApp
        - ./mvnw clean package -DskipTests=true dockerfile:build

deploy_auth-service:
    stage: deploy
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/auth-service
        - ./mvnw clean package -DskipTests=true dockerfile:build

deploy_configServer:
    stage: deploy
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/configServer
        - ./mvnw clean package -DskipTests=true dockerfile:build


deploy_eureckaServer:
    stage: deploy
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/eureka-service
        - ./mvnw clean package -DskipTests=true dockerfile:build
        - ./mvnw dockerfile:push

deploy_feedInfoService:
    stage: deploy
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/feedInfoService
        - ./mvnw clean package -DskipTests=true dockerfile:build
        - ./mvnw dockerfile:push

deploy_personneClient:
    stage: deploy
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/personne-client
        - ./mvnw clean package -DskipTests=true dockerfile:build
        - ./mvnw dockerfile:push

deploy_personneService:
    stage: deploy
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/personne-service
        - ./mvnw clean package -DskipTests=true dockerfile:build
        - ./mvnw dockerfile:push

deploy_webApp:
    stage: deploy
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/webApp
        - ./mvnw clean package -DskipTests=true dockerfile:build
        - ./mvnw dockerfile:push






buildAndroid:
    stage: build_Android
    image: jpkrause/react-native-gitlab-ci-build
    script:
        - cd app
        - pwd
        - export GRADLE_USER_HOME=$(pwd)/.gradle
        - chmod +x ./android/gradlew
        - npm config set registry https://registry.npmjs.org/  
        - npm install
        - react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/  
        - cd android && ./gradlew assembleRelease -x bundleReleaseJsAndAssets
        - ls ./app/build/outputs/apk/
        - jarsigner -verbose -storepass "$jarsignpassword" -keystore /builds/galoat/ReactNativeApp/app/android/app/my-release-key.keystore ./app/build/outputs/apk/app-release-unsigned.apk  alias_name  
        - cd /opt/android-sdk-linux/build-tools/26.0.2
        - mkdir -p $CI_PROJECT_DIR/deliverables  
        - ./zipalign -f -v 4 /builds/galoat/ReactNativeApp/app/android/app/build/outputs/apk/app-release-unsigned.apk $CI_PROJECT_DIR/deliverables/app.apk  
        - cd  $CI_PROJECT_DIR/deliverables
        - ls
        - touch info.txt
        - echo "Build date          $(date)"                >> info.txt
        - echo "App version name    ${VERSION_NAME}"        >> info.txt
        - echo "App version code    ${VERSION_CODE}"        >> info.txt
        - echo "Git branch          ${CI_COMMIT_REF_NAME}"  >> info.txt
        - echo "Git commit          ${CI_COMMIT_SHA}"       >> info.txt
        - echo "Gitlab pipeline     ${CI_PIPELINE_ID}"      >> info.txt
    artifacts:
        name: "Deploy-Test_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
        paths:
            - deliverables
