image: twalter/maven-docker
services:
      - docker:dind
variables:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_DRIVER: overlay

cache:
      key: ${CI_PROJECT_ID}
      paths:
          - .gradle/
          - node_modules/ 
stages:
    - build
    - deploy
    - build_Android  
build_personneClient:
    stage: build
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/personne-client
        - ./mvnw clean package -DskipTests=true dockerfile:build 
deploy_personneClient:
    stage: deploy
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/personne-client
        - ./mvnw clean package -DskipTests=true dockerfile:build 
        - ./mvnw dockerfile:push
buildAndroid:
    stage: build_Android
    image: magiczvn/gitlab-ci-react-native-android
    script:
        - export GRADLE_USER_HOME=$(pwd)/.gradle
        - chmod +x ./android/gradlew
        - npm install
        - mv ./app/build/outputs/apk/app-debug.apk ../../app-debug.apk
    artifacts:
        paths:
                - app-debug.apk
