image: openjdk:8-jdk-alpine
services:
      - docker:dind
variables:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_DRIVER: overlay2

before_script:
        - docker login -u "$user_docker" -p "$password_docker"
stages:
    - build
    - deploy  
build_personneClient:
    stage: build
    script:
        - cd server/personne-client
        - ./mvnw clean package -DskipTests=true dockerfile:build 
deploy_personneClient:
    stage: deploy
    script:
        - cd server/personne-client
        - ./mvnw dockerfile:push
