image: twalter/maven-docker
services:
    - docker:dind
variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay

cache:
    key: ${CI_PROJECT_ID}
    paths:
        - .gradle/
        - node_modules/
stages:
    - build
    - deploy
    - build_Android
build_personneClient:
    stage: build
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/personne-client
        - ./mvnw clean package -DskipTests=true dockerfile:build


build_auth-service:
    stage: build
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/auth-service
        - ./mvnw clean package -DskipTests=true dockerfile:build



deploy_personneClient:
    stage: deploy
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/personne-client
        - ./mvnw clean package -DskipTests=true dockerfile:build
        - ./mvnw dockerfile:push

deploy_auth-service:
    stage: deploy
    script:
        - docker login -u "$user_docker" -p "$password_docker"
        - cd server/auth-service
        - ./mvnw clean package -DskipTests=true dockerfile:build
        - ./mvnw dockerfile:push


buildAndroid:
    stage: build_Android
    image: jpkrause/react-native-gitlab-ci-build
    script:
        - export GRADLE_USER_HOME=$(pwd)/.gradle
        - chmod +x ./android/gradlew
        - npm config set registry https://registry.npmjs.org/  
        - npm install
        - react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/  
        - cd android && ./gradlew assembleRelease -x bundleReleaseJsAndAssets
        - jarsigner -verbose -storepass "$jarsignpassword" -keystore app/my-release-key.keystore app/build/outputs/apk/app-release-unsigned.apk  alias_name  
        - cd /opt/android-sdk-linux/build-tools/26.0.2
        - ls 
        - sudo ln -sf zipalign /usr/bin/
        - cd 
        - ./zipalign -f -v 4 android/app/build/outputs/apk/app-release-unsigned.apk app.apk  
        - mkdir -p deliverables  
        - mv app.apk delivrables/app.apk  
        - touch ./deliverables/info.txt
        - echo "Build date          $(date)"                >> ./deliverables/info.txt
        - echo "App version name    ${VERSION_NAME}"        >> ./deliverables/info.txt
        - echo "App version code    ${VERSION_CODE}"        >> ./deliverables/info.txt
        - echo "Git branch          ${CI_COMMIT_REF_NAME}"  >> ./deliverables/info.txt
        - echo "Git commit          ${CI_COMMIT_SHA}"       >> ./deliverables/info.txt
        - echo "Gitlab pipeline     ${CI_PIPELINE_ID}"      >> ./deliverables/info.txt
    artifacts:
        name: "Deploy-Test_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
        paths:
            - android/delivrables
