version: '3'

services:
    mysql:
        image: mariadb
        container_name: mysql-user 
        volumes:
            - ./server/autodeploy/data/auth/db:/var/lib/mysql
              #            - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: test
            MYSQL_PASSWORD: password
            MYSQL_USER: sa
        ports:
                - "3307:3306"
    mysqlFeed:
        image: mariadb
        container_name: mysql-feedInfo
        volumes:
            - ./server/autodeploy/data/feed/db:/var/lib/mysql
              #            - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: test
            MYSQL_PASSWORD: password
            MYSQL_USER: sa
        ports:
                - "3308:3306"

