- hosts: all
  become: true
  remote_user: root
  roles:
  tasks:
     - file: path=/app/docker state=directory
     - copy:
           src: ../../docker-compose.yml
           dest: /app/docker
     - name: copy data files
         command: cp -r ../data /app/autodeploy/data
    
     -  name: execute docker commpose
        shell: docker-compose up -d
        args:
            chdir: /app/docker

  copy: src=/home/vagrant/dist/ dest=/usr/share/nginx/html directory_mode=yes