
version: '3.1'
services:
#    mongo:
#        image: "mongo:latest"
#        volumes:
#            - ./mongodb/db:/data/db
#        ports:
#            - "27017:27017"
    config-server:
        image: "galoat/config-service"
        container_name: config-server
        expose:
            - 8888
        ports:
           - 8888:8888


    eurecka-service:
        image: "galoat/eurecka-service"
        ports:
            - 8761:8761
        expose:
            - 8761
        links:
          - config-server
        depends_on:
          - config-server
        entrypoint: ["./wait-for-it.sh","config-server:8888","--timeout=60","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]



  #  personne-service:
  #    image: "galoat/personne-service"
  #    container_name: "personne-service"
  #    expose:
  #        - "8001"
  #    ports:
  #       - "8001:8001"
  #    networks:
  #        - spring-cloud-network

networks:
    spring-cloud-network:
        driver: bridge
