
version: '2'
services:
    config-server:
        image: "galoat/config-service"
        container_name: config-server
        networks:
              - discover
        restart: always

    discovery-server:
        image: "galoat/eurecka-service"
        container_name: discovery-server
        networks:
            - discover
        restart: always
        entrypoint: ["./wait-for-it.sh","config-server:8888","--timeout=120","--","java", "-jar","/app.jar"]

    personne-service:
      image: galoat/personne-service
      container_name: personne-service
      networks:
          - discover
      environment:
            - JVM_OPTS=-Xmx12g -Xms12g -XX:MaxPermSize=512m
      restart: always
      entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=120","--","java","-jar","/app.jar"]


    personne-client:
      image: galoat/personne-client
      container_name: personne-client
      ports:
          - 9999:9999
      networks:
          - discover
          - auth
      environment:
            - JVM_OPTS=-Xmx12g -Xms12g -XX:MaxPermSize=512m
      restart: always
      expose:
        - 9999
      entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=120","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

    auth-service :
      image: galoat/oauth
      container_name: auth-service
      ports:
          - 9191:9191
      networks:
           - discover
           - auth
           - authDb
      environment:
            - JVM_OPTS=-Xmx12g -Xms12g -XX:MaxPermSize=512m
      restart: always
      expose:
        - 9191
      entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=120","--","java",  "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

    webApp :
      image: galoat/webapp
      container_name: webapp
      ports:
          - 8008:8008
      networks:
           - discover
           - auth
      environment:
            - JVM_OPTS=-Xmx12g -Xms12g -XX:MaxPermSize=512m
      restart: always
      expose:
        - 8008
      entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=120","--","java", "-jar","/app.jar"]

    feedInfo:
        image: galoat/feedinfo
        container_name: feedInfo
        networks:
                - discover
                - auth
                - feedDb
        environment:
              - JVM_OPTS=-Xmx12g -Xms12g -XX:MaxPermSize=512m
        restart: always
        entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=300","--","java", "-jar","/app.jar"]



    mysql-auth:
        image: mariadb
        container_name: mysql-auth
        networks:
                  - authDb
        volumes:
            - ./autodeploy/data/auth/dumpProd.sql:/docker-entrypoint-initdb.d/dump.sql
            - ./autodeploy/data/auth/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: user
            MYSQL_PASSWORD: password
            MYSQL_USER: sa


    mysql-feedinfo:
        image: mariadb
        container_name: mysql-feedinfo
        volumes:
            - ./autodeploy/data/feed/db:/var/lib/mysql
            - ./autodeploy/data/feed/dumpProd.sql:/docker-entrypoint-initdb.d/dump.sql
        networks:
          - feedDb
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: feedinfo
            MYSQL_PASSWORD: password
            MYSQL_USER: sa

networks:
  discover:
    driver: bridge
  auth:
      driver: bridge
  authDb:
      driver: bridge
  feedDb:
      driver: bridge
