
version: '2'
services:
    config-server:
        image: "galoat/config-service"
        container_name: config-server
        mem_limit: 256M
        networks:
              - discover
        restart:  on-failure

    discovery-server:
        image: "galoat/eurecka-service"
        container_name: discovery-server
        mem_limit: 256M
        networks:
            - discover
        restart:  on-failure
        entrypoint: ["./wait-for-it.sh","config-server:8888","--timeout=4000","--","java", "-XshowSettings:vm","-XX:MaxRAMPercentage=90", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

    personne-service:
      image: galoat/personne-service
      container_name: personne-service
      mem_limit: 256M
      networks:
          - discover
      restart:  on-failure
      entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=4000","--","java", "-XshowSettings:vm","-XX:MaxRAMPercentage=90", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]


    personne-client:
      image: galoat/personne-client
      container_name: personne-client
      mem_limit: 300M
      ports:
          - 9999:9999
      networks:
          - discover
          - auth
      restart:  on-failure
      expose:
        - 9999
      entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=4000","--","java", "-XshowSettings:vm","-XX:MaxRAMPercentage=90", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

    auth-service :
      image: galoat/oauth
      container_name: auth-service
      mem_limit: 256M
      ports:
          - 9191:9191
      networks:
           - discover
           - auth
           - authDb
      restart:  on-failure
      expose:
        - 9191
      entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=4000","--","java", "-XshowSettings:vm","-XX:MaxRAMPercentage=90", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

    webApp :
      image: galoat/webapp
      container_name: webapp
      mem_limit: 256M
      ports:
          - 8008:8008
      networks:
           - discover
           - auth
      restart:  on-failure
      expose:
        - 8008
      entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=4000","--","java", "-XshowSettings:vm","-XX:MaxRAMPercentage=90", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

    feedInfo:
        image: galoat/feedinfo
        container_name: feedInfo
        mem_limit: 300M
        restart:  on-failure
        networks:
                - discover
                - auth
                - feedDb
        restart:  on-failure
        entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=4000","--","java", "-XshowSettings:vm","-XX:MaxRAMPercentage=90", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]



    mysql-auth:
        image: mariadb
        container_name: mysql-auth
        mem_limit: 256M
        restart:  on-failure
        networks:
                  - authDb
        volumes:
            - ./autodeploy/data/auth/dumpProd.sql:/docker-entrypoint-initdb.d/dump.sql
            - ./autodeploy/data/auth/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: user
            MYSQL_PASSWORD: password
            MYSQL_USER: sa


    mysql-feedinfo:
        image: mariadb
        container_name: mysql-feedinfo
        mem_limit: 256M
        volumes:
            - ./autodeploy/data/feed/db:/var/lib/mysql
            - ./autodeploy/data/feed/dumpProd.sql:/docker-entrypoint-initdb.d/dump.sql
        networks:
          - feedDb
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: feedinfo
            MYSQL_PASSWORD: password
            MYSQL_USER: sa

networks:
  discover:
    driver: bridge
  auth:
      driver: bridge
  authDb:
      driver: bridge
  feedDb:
      driver: bridge
