
version: '3'
services:
#    mongo:
#        image: "mongo:latest"
#        volumes:
#            - ./mongodb/db:/data/db
#        ports:
#            - "27017:27017"
    config-server:
        image: "galoat/config-service"
        container_name: "configService"
        expose:
            - "8888"
        ports:
           - "8888:8888"
        networks:
            - spring-cloud-network
    eurecka-service:
        image: "galoat/eurecka-service"
        ports:
            - "8761:8761"
        expose:
            - "8761"
        networks:
            - spring-cloud-network
        links:
            - config-server:config-server

networks:
    spring-cloud-network:
        driver: bridge
